# Generated by Django 2.1.7 on 2019-03-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='creater_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='last_udated_time',
            new_name='last_updated_time',
        ),
    ]
