# Generated by Django 2.1.7 on 2019-03-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
